### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [OmarAlFarajat/Unity-POV-Graph#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by OmarAlFarajat** [comment]
@suprafun Done. Let me know if you have any questions. It's admittedly old clunky code that isn't implemented using Unity's Editor Scripting tools as it should be.

**Comment by OmarAlFarajat** [comment]
@suprafun Also, I made a write-up here that explains it a little bit: https://omaralfarajat.github.io/projects/povgraph
